### ISSUE TITLE
No new case counts since 5/22

### ISSUE THREAD

**Issue by silfreed** [patch-e/coronacharts#1]
It looks like the DoH scraping hasn't been working since May 22nd:
![Screen Shot 2020-06-03 at 10 19 48 AM](https://user-images.githubusercontent.com/436861/83648229-cd301280-a583-11ea-814b-5ea2acf0e7ee.png)

**Comment by patch-e** [comment]
Thanks for the heads up, resolved. The DOH site changed their site markup yet again :( I populated the missing data but am missing stats for 6/2, so the stats for 6/1 repeat for 6/2 currently.

https://github.com/patch-e/coronacharts/commit/db4e7c7e72a0480384f52ca887c92a10cc0edec4

**Comment by patch-e** [comment]
As of 6/8/2020, the PA Department of Health has completely changed the COVID-19 cases page. The county stats are no longer within the page's HTML and instead are now offloaded to a PDF file that has a different file name everyday.

This effectively stops my county COVID-19 tracker. I will not be tweaking the fetch process to deal with scraping data from PDFs.
